language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk11

matrix:
  allow_failures:
    - julia_version: nightly
    - os: windows
    - os: osx

notifications:
  email: false
